before_install:
  - sudo apt-get update -qq
  - sudo apt-get install pkg-config libxml2-dev libxslt1-dev
  - |
    if [[ "$LUA" == "lua5.3" ]]; then
      wget http://www.lua.org/ftp/lua-5.3.2.tar.gz -O lua.tar.gz
      tar -xvzf lua.tar.gz
      cd lua-*
      (cd src && make SYSCFLAGS="-DLUA_USE_LINUX -ULUA_COMPAT_5_2" SYSLIBS="-Wl,-E -ldl -lreadline" LUA_A=liblua5.3.so MYCFLAGS="-fPIC" RANLIB=: AR="gcc -shared -ldl -o" liblua5.3.so) || exit 1
      sudo make INSTALL_TOP=/usr/ INSTALL_INC=${LUA_INCDIR} TO_LIB=liblua5.3.so linux install || exit 1
      cd ..
    else
      sudo apt-get install $LUA
      sudo apt-get install $LUA_DEV
    fi


env:
  matrix:
    - LUA=lua5.1 LUA_DEV=liblua5.1-dev LUA_INCDIR=/usr/include/lua5.1 LUALIB=-llua5.1 LUA_VER=5.1
    - LUA=lua5.2 LUA_DEV=liblua5.2-dev LUA_INCDIR=/usr/include/lua5.2 LUALIB=-llua5.2 LUA_VER=5.2
    - LUA=luajit LUA_DEV=libluajit-5.1-dev LUA_INCDIR=/usr/include/luajit-2.0 LUALIB=-lluajit-5.1 LUA_VER=5.1


language: c
compiler:
  - gcc

script:
  - make && sudo make install && make check

after_script:
  - cat regression.diffs || true
